name: Build and Deploy
on:
  schedule:
    - cron:  '* * * * *'  
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'save variable'    
        shell: bash
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA") && echo $git_hash
